name: Demo to automate PR

on:
    push:
        branches:
               - main
env:
  NAME_OF_AUTHOR: Bhavya            

jobs:
    updateAuthor:
        runs-on: ubuntu-latest
        steps:
          - name: checking out code
            uses: actions/checkout@main

          - name: extract git commit data
            uses: Bhavyakotti/customworkflow@main

          - name: Update author information
            run: echo ${{ env.NAME_OF_AUTHOR}} 

          - name: Raise PR
            uses: peter-evans/create-pull-request@main
            with: 
               branch: "auto-pr-branch"
               base: main
               title: "demo for auto pr"
               committer: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}">
               author: ${{ env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}">
               body:
                This is to show automatic PR creation
               token: ${{ secrets.GITHUB_TOKEN}}
               delete-branch: true 